### ISSUE TITLE
plans for chunked uploads?

### ISSUE THREAD

**Issue by esoth** [collective/collective.upload#27]
Just wondering if the status of plans for this. I see it listed as a future feature - is it still planned? I tried simply adding the maxChunkSize option and this does upload in chunks, but each chunk makes a call to Media_Uploader - creating an entirely new file in Plone. I guess to get it to do one file this class would have to know that it's chunked and append to a stream, or at least find content in that folder with the same id.

**Comment by rodfersou** [comment]
We are using sequential uploads, need a code review with this in mind.

Maybe after last changes (adding a input hidden with filename) this is possible now.

**Comment by rodfersou** [comment]
@esoth could you please describe a scenario where chunked uploads is a good thing?

**Comment by ewohnlich** [comment]
It was a feature we wanted for uploading very large files - any network interruption or a user becoming impatient means no progress is made unless you are uploading in chunks. I ended up creating a new package that uses that jQuery plugin https://github.com/imsweb/ims.upload/. In addition to providing a backend to recombine the chunks it makes significant front end changes and satisfies some tangential requirements the client had, so take from it what you will, if anything.

That said, since I started my own project please don't keep this open for my sake :)
